/*jslint */
/*global AdobeEdge: false, window: false, document: false, console:false, alert: false */
(function (compId) {

    "use strict";
    var im='images/',
        aud='media/',
        vid='media/',
        js='js/',
        fonts = {
        },
        opts = {
            'gAudioPreloadPreference': 'auto',
            'gVideoPreloadPreference': 'auto'
        },
        resources = [
        ],
        scripts = [
            js+"jquery-1.7.1.min.js"
        ],
        symbols = {
            "stage": {
                version: "5.0.0",
                minimumCompatibleVersion: "5.0.0",
                build: "5.0.0.375",
                scaleToFit: "none",
                centerStage: "none",
                resizeInstances: false,
                content: {
                    dom: [
                        {
                            id: 'bg',
                            type: 'image',
                            rect: ['0', 'auto', '3000px', '1500px', 'auto', '-28'],
                            fill: ["rgba(0,0,0,0)",'svg_floor4/bg.svg','0px','0px']
                        },
                        {
                            id: 'bg-top',
                            type: 'image',
                            rect: ['0', '0', '3016px', '53px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",'svg_floor4/bg-top.svg','0px','0px']
                        },
                        {
                            id: 'line',
                            type: 'image',
                            rect: ['1214', 'auto', '573px', '19px', 'auto', '74'],
                            fill: ["rgba(0,0,0,0)",'svg_floor4/line.svg','0px','0px'],
                            transform: [[],[],[],[],['51%','108%']]
                        },
                        {
                            id: 'man-fly',
                            display: 'block',
                            type: 'image',
                            rect: ['1459', 'auto', '82px', '89px', 'auto', '689'],
                            fill: ["rgba(0,0,0,0)",'svg_floor7/man-fly.svg','0px','0px'],
                            transform: [[],[],[],['-1']]
                        },
                        {
                            id: 'hero',
                            display: 'none',
                            type: 'image',
                            rect: ['1475', 'auto', '69px', '90px', 'auto', '93'],
                            fill: ["rgba(0,0,0,0)",'svg_floor4/hero.svg','0px','0px']
                        },
                        {
                            id: 'moneys',
                            display: 'none',
                            type: 'image',
                            rect: ['1695', 'auto', '36px', '54px', 'auto', '656'],
                            fill: ["rgba(0,0,0,0)",'svg_floor4/moneys.svg','0px','0px']
                        },
                        {
                            id: 'palms',
                            display: 'none',
                            type: 'image',
                            rect: ['625', 'auto', '317px', '344px', 'auto', '659'],
                            clip: 'rect(0px 317px 311px 0px)',
                            fill: ["rgba(0,0,0,0)",'svg_floor4/palms.svg','0px','0px']
                        },
                        {
                            id: 'man-right_and_cooler',
                            display: 'none',
                            type: 'image',
                            rect: ['1894', 'auto', '207px', '114px', 'auto', '471'],
                            fill: ["rgba(0,0,0,0)",'svg_floor4/man-right_and_cooler.svg','0px','0px']
                        },
                        {
                            id: 'moneys2',
                            display: 'none',
                            type: 'image',
                            rect: ['1232', 'auto', '36px', '54px', 'auto', '483'],
                            fill: ["rgba(0,0,0,0)",'svg_floor4/moneys.svg','0px','0px']
                        },
                        {
                            id: 'moneys2Copy',
                            display: 'none',
                            type: 'image',
                            rect: ['1268', 'auto', '36px', '54px', 'auto', '573'],
                            fill: ["rgba(0,0,0,0)",'svg_floor4/moneys.svg','0px','0px']
                        },
                        {
                            id: 'moneys2Copy3',
                            display: 'none',
                            type: 'image',
                            rect: ['1304', 'auto', '36px', '54px', 'auto', '483'],
                            fill: ["rgba(0,0,0,0)",'svg_floor4/moneys.svg','0px','0px']
                        },
                        {
                            id: 'moneys2Copy2',
                            display: 'none',
                            type: 'image',
                            rect: ['1340', 'auto', '36px', '54px', 'auto', '573'],
                            fill: ["rgba(0,0,0,0)",'svg_floor4/moneys.svg','0px','0px']
                        },
                        {
                            id: 'moneys2Copy5',
                            display: 'none',
                            type: 'image',
                            rect: ['1376', 'auto', '36px', '54px', 'auto', '483'],
                            fill: ["rgba(0,0,0,0)",'svg_floor4/moneys.svg','0px','0px']
                        },
                        {
                            id: 'moneys2Copy4',
                            display: 'none',
                            type: 'image',
                            rect: ['1412', 'auto', '36px', '54px', 'auto', '573'],
                            fill: ["rgba(0,0,0,0)",'svg_floor4/moneys.svg','0px','0px']
                        },
                        {
                            id: 'car',
                            display: 'none',
                            type: 'image',
                            rect: ['827', 'auto', '252px', '97px', 'auto', '622'],
                            fill: ["rgba(0,0,0,0)",'svg_floor4/car.svg','0px','0px']
                        },
                        {
                            id: 'girl',
                            display: 'none',
                            type: 'image',
                            rect: ['784', 'auto', '56px', '89px', 'auto', '651'],
                            fill: ["rgba(0,0,0,0)",'svg_floor4/girl.svg','0px','0px']
                        }
                    ],
                    style: {
                        '${Stage}': {
                            isStage: true,
                            rect: ['null', 'null', '3000', '100%', 'auto', 'auto'],
                            overflow: 'hidden',
                            fill: ["rgba(66,0,65,1.00)"]
                        }
                    }
                },
                timeline: {
                    duration: 9750,
                    autoPlay: true,
                    labels: {
                        "start": 0,
                        "part0": 1548,
                        "part1": 4039,
                        "part2": 6196,
                        "part3": 8167,
                        "end": 9750
                    },
                    data: [
                        [
                            "eid82",
                            "left",
                            8385,
                            422,
                            "linear",
                            "${moneys2Copy4}",
                            '1412px',
                            '1402px'
                        ],
                        [
                            "eid89",
                            "left",
                            8807,
                            317,
                            "linear",
                            "${moneys2Copy4}",
                            '1402px',
                            '1403px'
                        ],
                        [
                            "eid113",
                            "left",
                            9124,
                            626,
                            "linear",
                            "${moneys2Copy4}",
                            '1403px',
                            '1061px'
                        ],
                        [
                            "eid42",
                            "display",
                            0,
                            0,
                            "easeInQuad",
                            "${car}",
                            'none',
                            'none'
                        ],
                        [
                            "eid41",
                            "display",
                            5000,
                            0,
                            "easeInQuad",
                            "${car}",
                            'none',
                            'block'
                        ],
                        [
                            "eid2",
                            "bottom",
                            0,
                            1500,
                            "linear",
                            "${man-fly}",
                            '689px',
                            '94px'
                        ],
                        [
                            "eid116",
                            "bottom",
                            9124,
                            626,
                            "linear",
                            "${man-fly}",
                            '94px',
                            '-307px'
                        ],
                        [
                            "eid52",
                            "left",
                            6400,
                            523,
                            "easeInSine",
                            "${moneys2Copy2}",
                            '1340px',
                            '1337px'
                        ],
                        [
                            "eid67",
                            "left",
                            6923,
                            476,
                            "easeInSine",
                            "${moneys2Copy2}",
                            '1337px',
                            '1334px'
                        ],
                        [
                            "eid109",
                            "left",
                            9124,
                            626,
                            "linear",
                            "${moneys2Copy2}",
                            '1334px',
                            '999px'
                        ],
                        [
                            "eid20",
                            "display",
                            0,
                            0,
                            "easeOutBounce",
                            "${moneys2Copy2}",
                            'none',
                            'none'
                        ],
                        [
                            "eid46",
                            "display",
                            6400,
                            0,
                            "easeOutBounce",
                            "${moneys2Copy2}",
                            'none',
                            'block'
                        ],
                        [
                            "eid12",
                            "left",
                            2138,
                            362,
                            "linear",
                            "${moneys}",
                            '1695px',
                            '1700px'
                        ],
                        [
                            "eid54",
                            "left",
                            6923,
                            476,
                            "easeInSine",
                            "${moneys}",
                            '1700px',
                            '1697px'
                        ],
                        [
                            "eid84",
                            "left",
                            8807,
                            317,
                            "linear",
                            "${moneys}",
                            '1697px',
                            '1596px'
                        ],
                        [
                            "eid121",
                            "left",
                            9124,
                            626,
                            "linear",
                            "${moneys}",
                            '1596px',
                            '1253px'
                        ],
                        [
                            "eid70",
                            "display",
                            0,
                            0,
                            "easeInSine",
                            "${girl}",
                            'none',
                            'none'
                        ],
                        [
                            "eid69",
                            "display",
                            7198,
                            0,
                            "easeInSine",
                            "${girl}",
                            'none',
                            'block'
                        ],
                        [
                            "eid115",
                            "left",
                            9124,
                            626,
                            "linear",
                            "${man-fly}",
                            '1459px',
                            '1142px'
                        ],
                        [
                            "eid33",
                            "left",
                            4250,
                            545,
                            "easeInQuad",
                            "${moneys2Copy}",
                            '1268px',
                            '1267px'
                        ],
                        [
                            "eid62",
                            "left",
                            6923,
                            476,
                            "easeInSine",
                            "${moneys2Copy}",
                            '1267px',
                            '1266px'
                        ],
                        [
                            "eid120",
                            "left",
                            9124,
                            626,
                            "linear",
                            "${moneys2Copy}",
                            '1266px',
                            '1125px'
                        ],
                        [
                            "eid4",
                            "display",
                            0,
                            0,
                            "linear",
                            "${hero}",
                            'none',
                            'none'
                        ],
                        [
                            "eid3",
                            "display",
                            1500,
                            0,
                            "linear",
                            "${hero}",
                            'none',
                            'block'
                        ],
                        [
                            "eid7",
                            "display",
                            1613,
                            0,
                            "linear",
                            "${hero}",
                            'block',
                            'block'
                        ],
                        [
                            "eid100",
                            "display",
                            9124,
                            0,
                            "linear",
                            "${hero}",
                            'block',
                            'none'
                        ],
                        [
                            "eid18",
                            "display",
                            0,
                            0,
                            "easeOutBounce",
                            "${moneys2}",
                            'none',
                            'none'
                        ],
                        [
                            "eid24",
                            "display",
                            4089,
                            0,
                            "easeOutBounce",
                            "${moneys2}",
                            'none',
                            'block'
                        ],
                        [
                            "eid49",
                            "left",
                            6250,
                            465,
                            "easeInSine",
                            "${moneys2Copy3}",
                            '1304px',
                            '1302px'
                        ],
                        [
                            "eid64",
                            "left",
                            6923,
                            476,
                            "easeInSine",
                            "${moneys2Copy3}",
                            '1302px',
                            '1301px'
                        ],
                        [
                            "eid107",
                            "left",
                            9124,
                            626,
                            "linear",
                            "${moneys2Copy3}",
                            '1301px',
                            '967px'
                        ],
                        [
                            "eid51",
                            "rotateZ",
                            6400,
                            523,
                            "easeInSine",
                            "${moneys2Copy2}",
                            '0deg',
                            '-7deg'
                        ],
                        [
                            "eid66",
                            "rotateZ",
                            6923,
                            476,
                            "easeInSine",
                            "${moneys2Copy2}",
                            '-7deg',
                            '-11deg'
                        ],
                        [
                            "eid93",
                            "rotateZ",
                            8807,
                            317,
                            "linear",
                            "${moneys2Copy2}",
                            '-11deg',
                            '-54deg'
                        ],
                        [
                            "eid125",
                            "bottom",
                            8214,
                            1036,
                            "easeOutBounce",
                            "${palms}",
                            '659px',
                            '59px'
                        ],
                        [
                            "eid48",
                            "rotateZ",
                            6250,
                            465,
                            "easeInSine",
                            "${moneys2Copy3}",
                            '0deg',
                            '-7deg'
                        ],
                        [
                            "eid63",
                            "rotateZ",
                            6923,
                            476,
                            "easeInSine",
                            "${moneys2Copy3}",
                            '-7deg',
                            '-11deg'
                        ],
                        [
                            "eid95",
                            "rotateZ",
                            8807,
                            317,
                            "linear",
                            "${moneys2Copy3}",
                            '-11deg',
                            '-54deg'
                        ],
                        [
                            "eid106",
                            "scaleY",
                            9124,
                            0,
                            "linear",
                            "${man-fly}",
                            '1',
                            '1'
                        ],
                        [
                            "eid79",
                            "left",
                            8214,
                            456,
                            "linear",
                            "${moneys2Copy5}",
                            '1376px',
                            '1367px'
                        ],
                        [
                            "eid111",
                            "left",
                            9124,
                            626,
                            "linear",
                            "${moneys2Copy5}",
                            '1367px',
                            '1030px'
                        ],
                        [
                            "eid80",
                            "bottom",
                            8385,
                            422,
                            "linear",
                            "${moneys2Copy4}",
                            '573px',
                            '76px'
                        ],
                        [
                            "eid87",
                            "bottom",
                            8807,
                            317,
                            "linear",
                            "${moneys2Copy4}",
                            '76px',
                            '10px'
                        ],
                        [
                            "eid114",
                            "bottom",
                            9124,
                            626,
                            "linear",
                            "${moneys2Copy4}",
                            '10px',
                            '-428px'
                        ],
                        [
                            "eid28",
                            "bottom",
                            4250,
                            545,
                            "easeInQuad",
                            "${moneys2Copy}",
                            '573px',
                            '107px'
                        ],
                        [
                            "eid36",
                            "bottom",
                            4795,
                            509,
                            "easeInQuad",
                            "${moneys2Copy}",
                            '107px',
                            '69px'
                        ],
                        [
                            "eid61",
                            "bottom",
                            6923,
                            476,
                            "easeInSine",
                            "${moneys2Copy}",
                            '69px',
                            '49px'
                        ],
                        [
                            "eid96",
                            "bottom",
                            8807,
                            317,
                            "linear",
                            "${moneys2Copy}",
                            '49px',
                            '-171px'
                        ],
                        [
                            "eid117",
                            "bottom",
                            9124,
                            626,
                            "linear",
                            "${moneys2Copy}",
                            '-171px',
                            '-349px'
                        ],
                        [
                            "eid57",
                            "left",
                            6923,
                            476,
                            "easeInSine",
                            "${moneys2}",
                            '1232px',
                            '1233px'
                        ],
                        [
                            "eid119",
                            "left",
                            9124,
                            626,
                            "linear",
                            "${moneys2}",
                            '1233px',
                            '1092px'
                        ],
                        [
                            "eid81",
                            "rotateZ",
                            8385,
                            422,
                            "linear",
                            "${moneys2Copy4}",
                            '0deg',
                            '-11deg'
                        ],
                        [
                            "eid88",
                            "rotateZ",
                            8807,
                            317,
                            "linear",
                            "${moneys2Copy4}",
                            '-11deg',
                            '-54deg'
                        ],
                        [
                            "eid11",
                            "rotateZ",
                            2138,
                            362,
                            "linear",
                            "${moneys}",
                            '0deg',
                            '5deg'
                        ],
                        [
                            "eid39",
                            "rotateZ",
                            4795,
                            509,
                            "easeInQuad",
                            "${moneys}",
                            '5deg',
                            '-5deg'
                        ],
                        [
                            "eid56",
                            "rotateZ",
                            6923,
                            476,
                            "easeInSine",
                            "${moneys}",
                            '-5deg',
                            '-11deg'
                        ],
                        [
                            "eid86",
                            "rotateZ",
                            8807,
                            317,
                            "linear",
                            "${moneys}",
                            '-11deg',
                            '-55deg'
                        ],
                        [
                            "eid78",
                            "rotateZ",
                            8214,
                            456,
                            "linear",
                            "${moneys2Copy5}",
                            '0deg',
                            '-11deg'
                        ],
                        [
                            "eid91",
                            "rotateZ",
                            8807,
                            317,
                            "linear",
                            "${moneys2Copy5}",
                            '-11deg',
                            '-54deg'
                        ],
                        [
                            "eid19",
                            "display",
                            0,
                            0,
                            "easeOutBounce",
                            "${moneys2Copy5}",
                            'none',
                            'none'
                        ],
                        [
                            "eid75",
                            "display",
                            8214,
                            0,
                            "linear",
                            "${moneys2Copy5}",
                            'none',
                            'block'
                        ],
                        [
                            "eid104",
                            "scaleX",
                            9124,
                            0,
                            "linear",
                            "${man-fly}",
                            '-1',
                            '-1'
                        ],
                        [
                            "eid47",
                            "bottom",
                            6250,
                            465,
                            "easeInSine",
                            "${moneys2Copy3}",
                            '483px',
                            '73px'
                        ],
                        [
                            "eid65",
                            "bottom",
                            6923,
                            476,
                            "easeInSine",
                            "${moneys2Copy3}",
                            '73px',
                            '55px'
                        ],
                        [
                            "eid94",
                            "bottom",
                            8807,
                            317,
                            "linear",
                            "${moneys2Copy3}",
                            '55px',
                            '-126px'
                        ],
                        [
                            "eid108",
                            "bottom",
                            9124,
                            626,
                            "linear",
                            "${moneys2Copy3}",
                            '-126px',
                            '-547px'
                        ],
                        [
                            "eid44",
                            "bottom",
                            5000,
                            1148,
                            "easeOutBounce",
                            "${car}",
                            '622px',
                            '92px'
                        ],
                        [
                            "eid9",
                            "rotateZ",
                            2138,
                            362,
                            "linear",
                            "${line}",
                            '0deg',
                            '4deg'
                        ],
                        [
                            "eid34",
                            "rotateZ",
                            4795,
                            509,
                            "easeInQuad",
                            "${line}",
                            '4deg',
                            '-6deg'
                        ],
                        [
                            "eid53",
                            "rotateZ",
                            6923,
                            476,
                            "easeInSine",
                            "${line}",
                            '-6deg',
                            '-11deg'
                        ],
                        [
                            "eid83",
                            "rotateZ",
                            8807,
                            317,
                            "linear",
                            "${line}",
                            '-11deg',
                            '-53deg'
                        ],
                        [
                            "eid17",
                            "bottom",
                            2500,
                            1500,
                            "easeOutBounce",
                            "${man-right_and_cooler}",
                            '471px',
                            '91px'
                        ],
                        [
                            "eid8",
                            "bottom",
                            1613,
                            525,
                            "linear",
                            "${moneys}",
                            '656px',
                            '93px'
                        ],
                        [
                            "eid10",
                            "bottom",
                            2138,
                            362,
                            "linear",
                            "${moneys}",
                            '93px',
                            '78px'
                        ],
                        [
                            "eid40",
                            "bottom",
                            4795,
                            509,
                            "easeInQuad",
                            "${moneys}",
                            '78px',
                            '114px'
                        ],
                        [
                            "eid55",
                            "bottom",
                            6923,
                            476,
                            "easeInSine",
                            "${moneys}",
                            '114px',
                            '133px'
                        ],
                        [
                            "eid85",
                            "bottom",
                            8807,
                            317,
                            "linear",
                            "${moneys}",
                            '133px',
                            '264px'
                        ],
                        [
                            "eid122",
                            "bottom",
                            9124,
                            626,
                            "linear",
                            "${moneys}",
                            '264px',
                            '-187px'
                        ],
                        [
                            "eid6",
                            "display",
                            0,
                            0,
                            "linear",
                            "${man-fly}",
                            'block',
                            'block'
                        ],
                        [
                            "eid5",
                            "display",
                            1500,
                            0,
                            "linear",
                            "${man-fly}",
                            'block',
                            'none'
                        ],
                        [
                            "eid101",
                            "display",
                            9124,
                            0,
                            "linear",
                            "${man-fly}",
                            'none',
                            'block'
                        ],
                        [
                            "eid50",
                            "bottom",
                            6400,
                            523,
                            "easeInSine",
                            "${moneys2Copy2}",
                            '573px',
                            '77px'
                        ],
                        [
                            "eid68",
                            "bottom",
                            6923,
                            476,
                            "easeInSine",
                            "${moneys2Copy2}",
                            '77px',
                            '62px'
                        ],
                        [
                            "eid92",
                            "bottom",
                            8807,
                            317,
                            "linear",
                            "${moneys2Copy2}",
                            '62px',
                            '-82px'
                        ],
                        [
                            "eid110",
                            "bottom",
                            9124,
                            626,
                            "linear",
                            "${moneys2Copy2}",
                            '-82px',
                            '-508px'
                        ],
                        [
                            "eid124",
                            "display",
                            0,
                            0,
                            "linear",
                            "${palms}",
                            'none',
                            'none'
                        ],
                        [
                            "eid123",
                            "display",
                            8214,
                            0,
                            "linear",
                            "${palms}",
                            'none',
                            'block'
                        ],
                        [
                            "eid14",
                            "display",
                            0,
                            0,
                            "linear",
                            "${moneys}",
                            'none',
                            'none'
                        ],
                        [
                            "eid13",
                            "display",
                            1613,
                            0,
                            "linear",
                            "${moneys}",
                            'none',
                            'block'
                        ],
                        [
                            "eid16",
                            "display",
                            0,
                            0,
                            "linear",
                            "${man-right_and_cooler}",
                            'none',
                            'none'
                        ],
                        [
                            "eid15",
                            "display",
                            2500,
                            0,
                            "linear",
                            "${man-right_and_cooler}",
                            'none',
                            'block'
                        ],
                        [
                            "eid27",
                            "rotateZ",
                            4089,
                            564,
                            "easeInQuad",
                            "${moneys2}",
                            '0deg',
                            '4deg'
                        ],
                        [
                            "eid37",
                            "rotateZ",
                            4795,
                            509,
                            "easeInQuad",
                            "${moneys2}",
                            '4deg',
                            '-6deg'
                        ],
                        [
                            "eid59",
                            "rotateZ",
                            6923,
                            476,
                            "easeInSine",
                            "${moneys2}",
                            '-6deg',
                            '-10deg'
                        ],
                        [
                            "eid99",
                            "rotateZ",
                            8807,
                            317,
                            "linear",
                            "${moneys2}",
                            '-10deg',
                            '-54deg'
                        ],
                        [
                            "eid23",
                            "display",
                            0,
                            0,
                            "easeOutBounce",
                            "${moneys2Copy4}",
                            'none',
                            'none'
                        ],
                        [
                            "eid76",
                            "display",
                            8385,
                            0,
                            "linear",
                            "${moneys2Copy4}",
                            'none',
                            'block'
                        ],
                        [
                            "eid22",
                            "display",
                            0,
                            0,
                            "easeOutBounce",
                            "${moneys2Copy}",
                            'none',
                            'none'
                        ],
                        [
                            "eid25",
                            "display",
                            4250,
                            0,
                            "easeOutBounce",
                            "${moneys2Copy}",
                            'none',
                            'block'
                        ],
                        [
                            "eid74",
                            "bottom",
                            7198,
                            930,
                            "easeOutBounce",
                            "${girl}",
                            '651px',
                            '91px'
                        ],
                        [
                            "eid29",
                            "rotateZ",
                            4250,
                            545,
                            "easeInQuad",
                            "${moneys2Copy}",
                            '0deg',
                            '4deg'
                        ],
                        [
                            "eid38",
                            "rotateZ",
                            4795,
                            509,
                            "easeInQuad",
                            "${moneys2Copy}",
                            '4deg',
                            '-6deg'
                        ],
                        [
                            "eid60",
                            "rotateZ",
                            6923,
                            476,
                            "easeInSine",
                            "${moneys2Copy}",
                            '-6deg',
                            '-11deg'
                        ],
                        [
                            "eid97",
                            "rotateZ",
                            8807,
                            317,
                            "linear",
                            "${moneys2Copy}",
                            '-11deg',
                            '-54deg'
                        ],
                        [
                            "eid21",
                            "display",
                            0,
                            0,
                            "easeOutBounce",
                            "${moneys2Copy3}",
                            'none',
                            'none'
                        ],
                        [
                            "eid45",
                            "display",
                            6250,
                            0,
                            "easeOutBounce",
                            "${moneys2Copy3}",
                            'none',
                            'block'
                        ],
                        [
                            "eid77",
                            "bottom",
                            8214,
                            456,
                            "linear",
                            "${moneys2Copy5}",
                            '483px',
                            '69px'
                        ],
                        [
                            "eid90",
                            "bottom",
                            8807,
                            317,
                            "linear",
                            "${moneys2Copy5}",
                            '69px',
                            '-39px'
                        ],
                        [
                            "eid112",
                            "bottom",
                            9124,
                            626,
                            "linear",
                            "${moneys2Copy5}",
                            '-39px',
                            '-468px'
                        ],
                        [
                            "eid26",
                            "bottom",
                            4089,
                            564,
                            "easeInQuad",
                            "${moneys2}",
                            '483px',
                            '110px'
                        ],
                        [
                            "eid35",
                            "bottom",
                            4795,
                            509,
                            "easeInQuad",
                            "${moneys2}",
                            '110px',
                            '65px'
                        ],
                        [
                            "eid58",
                            "bottom",
                            6923,
                            476,
                            "easeInSine",
                            "${moneys2}",
                            '65px',
                            '42px'
                        ],
                        [
                            "eid98",
                            "bottom",
                            8807,
                            317,
                            "linear",
                            "${moneys2}",
                            '42px',
                            '-210px'
                        ],
                        [
                            "eid118",
                            "bottom",
                            9124,
                            626,
                            "linear",
                            "${moneys2}",
                            '-210px',
                            '-391px'
                        ]
                    ]
                }
            }
        };

    AdobeEdge.registerCompositionDefn(compId, symbols, fonts, scripts, resources, opts);

    if (!window.edge_authoring_mode) AdobeEdge.getComposition(compId).load("floor4_edgeActions.js");
})("EDGE-16070390");
