// Generated by CoffeeScript 1.6.3
(function() {
  var init_popup, next_label_coord, scroll_data, timeline_1, use_transit;

  scroll_data = [
    {
      part0: 510,
      part1: 510,
      part2: 300,
      part3: 60,
      part4: 60,
      part5: 60
    }
  ];

  next_label_coord = 0;

  timeline_1 = null;

  window.i1start = function(sym) {
    if (timeline_1) {
      return;
    }
    sym.stop();
    return timeline_1 = sym;
  };

  $(document).ready(function() {
    var bottom_scroll, content_height, resize_screen_handler, scroll_creator_height, scroll_handler, top_scroll, total_delay, window_height, window_width;
    window_height = $(window).height();
    window_width = $(window).width();
    content_height = $('.content').height();
    scroll_creator_height = $('.scroll_creator').height();
    top_scroll = 0;
    bottom_scroll = 0;
    total_delay = scroll_data.reduce((function(prev, curr) {
      return prev + curr.delay;
    }), 0);
    resize_screen_handler = function() {
      window_height = $(window).height();
      window_width = $(window).width();
      $('.eighth_floor').css('height', window_height + 400 + 'px');
      return $('.popup1').css('top', window_height - 650 + 'px');
    };
    resize_screen_handler();
    $(window).on('resize', resize_screen_handler);
    scroll_handler = function() {
      var currentPosition, current_label, label_num, labels, next_label, next_label_num, stage, _is_scroll_down, _label_name, _top_scroll;
      _is_scroll_down = true;
      _top_scroll = $(window).scrollTop();
      if (_top_scroll === 0) {
        window.scroll(0, 20);
        if (_top_scroll === top_scroll) {
          top_scroll = 50;
        }
      }
      if (_top_scroll >= (20000 - window_height)) {
        console.log('bottom');
        window.scroll(0, 20000 - window_height - 40);
        top_scroll = 20000 - window_height - 60;
      }
      if (_top_scroll - top_scroll < 0 || _top_scroll < 0) {
        _is_scroll_down = false;
      }
      bottom_scroll = top_scroll + window_height;
      currentPosition = 0;
      if (timeline_1 === null) {
        return;
      }
      stage = timeline_1.getComposition().getStage();
      labels = stage.timelines['Default Timeline'].labels;
      if (stage) {
        currentPosition = stage.getPosition();
      }
      current_label = false;
      for (_label_name in labels) {
        if (labels[_label_name] === currentPosition) {
          current_label = _label_name;
        }
      }
      label_num = -1;
      if (current_label) {
        label_num = parseInt(current_label.substr(current_label.length - 1));
      }
      if (Math.abs(_top_scroll - top_scroll) < 50) {
        top_scroll = _top_scroll;
        return;
      }
      next_label_num = void 0;
      if (_is_scroll_down) {
        if (label_num < 5) {
          timeline_1.play();
          next_label_num = label_num + 1;
          if (current_label) {
            next_label = current_label.substring(0, current_label.length - 1) + next_label_num;
            next_label_coord = scroll_data[0][next_label];
            use_transit('.content', {
              top: -(370 - next_label_coord + 140) + 'px'
            });
          }
        }
      } else {
        if (label_num > 0) {
          timeline_1.playReverse();
          next_label_num = label_num - 1;
          if (current_label) {
            next_label = current_label.substring(0, current_label.length - 1) + next_label_num;
            next_label_coord = scroll_data[0][next_label];
            use_transit('.content', {
              top: -(370 - next_label_coord + 140) + 'px'
            });
          }
        }
      }
      return top_scroll = _top_scroll;
    };
    return $(window).scroll(scroll_handler);
  });

  use_transit = function(selector, animate_object) {
    if ($(document).transit === void 0) {
      return $.getScript('scripts/jquery.transit.min.js', function() {
        return $(selector).transition(animate_object);
      });
    } else {
      return $(selector).transition(animate_object);
    }
  };

  init_popup = function() {
    var close_btn, popup, read_btn;
    popup = $('.popup1');
    close_btn = $('.close_btn');
    read_btn = $('.read_btn');
    read_btn.css('display', 'block');
    close_btn.css('display', 'none');
    use_transit('.popup_content', {
      height: '0px'
    });
    use_transit('.popup1', {
      height: '100px'
    });
    read_btn.on('click', function() {
      read_btn.css('display', 'none');
      close_btn.css('display', 'block');
      use_transit('.popup_content', {
        height: '155px'
      });
      return use_transit('.popup1', {
        height: '190px'
      });
    });
    return close_btn.on('click', function() {
      read_btn.css('display', 'block');
      close_btn.css('display', 'none');
      use_transit('.popup_content', {
        height: '0px'
      });
      return use_transit('.popup1', {
        height: '100px'
      });
    });
  };

  init_popup();

}).call(this);

/*
//@ sourceMappingURL=__script.map
*/
