// Generated by CoffeeScript 1.6.3
(function() {
  var animation_functions, scroll_timeline, timeline_8;

  scroll_timeline = [
    {
      gap: 3690,
      delay: 3000
    }
  ];

  animation_functions = [];

  timeline_8 = null;

  window.i8start = function(sym) {
    sym.stop();
    return timeline_8 = sym;
  };

  $(document).ready(function() {
    var close_popup, content_height, enter_frame, floor_one_animation, floor_three_animation, floor_two_animation, hide_popup, init_popup, is_popup_visible, open_popup, scroll_creator_height, scroll_top, show_popup, timelines_controller, top_gap, total_delay, window_height, window_width;
    window_height = $(window).height();
    window_width = $(window).width();
    content_height = $('.content').height();
    scroll_creator_height = $('.scroll_creator').height();
    scroll_top = 0;
    total_delay = scroll_timeline.reduce((function(prev, curr) {
      return prev + curr.delay;
    }), 0);
    $(window).on('resize', function() {
      window_height = $(window).height();
      return window_width = $(window).width();
    });
    $(window).scroll(function() {
      return scroll_top = $(window).scrollTop();
    });
    top_gap = 0;
    enter_frame = function() {
      var can_scroll, i, top_delay, val, _bottom_gap, _i, _j, _len, _len1, _scroll_percent, _top_gap, _top_gap_from_bottom_gap;
      _scroll_percent = scroll_top / (scroll_creator_height - window_height);
      _top_gap = (window_height - content_height - total_delay) * _scroll_percent;
      if (_top_gap !== top_gap) {
        top_gap = _top_gap;
        top_delay = 0;
        _bottom_gap = -_top_gap + window_height;
        for (_i = 0, _len = scroll_timeline.length; _i < _len; _i++) {
          val = scroll_timeline[_i];
          if (_bottom_gap > (val.gap + val.delay)) {
            top_delay += val.delay;
          }
        }
        _top_gap += top_delay;
        can_scroll = -1;
        for (i = _j = 0, _len1 = scroll_timeline.length; _j < _len1; i = ++_j) {
          val = scroll_timeline[i];
          if (_bottom_gap > val.gap && _bottom_gap < (val.gap + val.delay)) {
            can_scroll = i;
          }
        }
        if (can_scroll === -1) {
          if (_top_gap > 0) {
            _top_gap = 0;
          }
          $('.content').css('top', _top_gap + 'px');
        } else {
          _top_gap_from_bottom_gap = -(scroll_timeline[can_scroll].gap - window_height - top_delay);
          if (_top_gap_from_bottom_gap > 0) {
            _top_gap_from_bottom_gap = 0;
          }
          $('.content').css('top', _top_gap_from_bottom_gap + 'px');
          timelines_controller(can_scroll);
        }
      }
      return requestAnimationFrame(enter_frame);
    };
    enter_frame();
    timelines_controller = function(floor_num) {
      var percent, _bottom_gap, _gap_from_animation_start;
      _bottom_gap = -top_gap + window_height;
      _gap_from_animation_start = _bottom_gap - scroll_timeline[floor_num].gap;
      percent = _gap_from_animation_start / scroll_timeline[floor_num].delay;
      return animation_functions[floor_num](percent);
    };
    floor_one_animation = function(percent) {
      var _total_time;
      if (timeline_8 === null) {
        return;
      }
      _total_time = 8000;
      timeline_8.stop(_total_time * percent);
      if (percent > 0.5) {
        return show_popup();
      } else {
        return hide_popup();
      }
    };
    animation_functions.push(floor_one_animation);
    floor_two_animation = function(percent) {
      return console.log(2);
    };
    animation_functions.push(floor_two_animation);
    floor_three_animation = function(percent) {
      return console.log(3);
    };
    animation_functions.push(floor_three_animation);
    is_popup_visible = true;
    show_popup = function() {
      if (!is_popup_visible) {
        $('.popup').fadeIn();
        return is_popup_visible = true;
      }
    };
    hide_popup = function() {
      if (is_popup_visible) {
        $('.popup').fadeOut();
        return is_popup_visible = false;
      }
    };
    open_popup = function() {
      $('.close_btn').css('display', 'block');
      $('.read_btn').css('display', 'none');
      $('.popup_content').animate({
        height: 56
      });
      $('.popup').animate({
        height: 75
      });
      return $('.popup').animate({
        height: 75
      });
    };
    close_popup = function() {
      $('.read_btn').css('display', 'block');
      $('.close_btn').css('display', 'none');
      $('.popup_content').animate({
        height: 0
      });
      return $('.popup').animate({
        height: 15
      });
    };
    init_popup = function() {
      close_popup();
      hide_popup();
      $('.close_btn').on('click', function() {
        return close_popup();
      });
      return $('.read_btn').on('click', function() {
        return open_popup();
      });
    };
    return init_popup();
  });

}).call(this);

/*
//@ sourceMappingURL=_script.map
*/
