// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    Tipped.create('.popup');
    $('.short-btn').on('click', function() {
      $('.short-btn').addClass('btn-selected');
      $('.long-btn').removeClass('btn-selected');
      $('.short').removeClass('hidden');
      return $('.long').addClass('hidden');
    });
    $('.long-btn').on('click', function() {
      $('.short-btn').removeClass('btn-selected');
      $('.long-btn').addClass('btn-selected');
      $('.short').addClass('hidden');
      return $('.long').removeClass('hidden');
    });
    $('.photo').on('mouseover', function() {
      return $('.sequence').fadeIn();
    });
    $('.sequence').on('mouseleave', function() {
      return $('.sequence').fadeOut();
    });
    return $('.sequence').on('mousemove', function(e) {
      var parentOffset, step, x;
      parentOffset = $(this).parent().offset();
      x = e.pageX - parentOffset.left;
      step = Math.round((x - 116) / (116 / 8)) * 232;
      return $('.sequence').css('background-position', step + 'px 0px');
    });
  });

}).call(this);

/*
//@ sourceMappingURL=script.map
*/
