// Generated by CoffeeScript 1.6.3
(function() {
  var is_next_play, next_label_coord, play_next, play_prev, scroll_data, timeStamp, timeline_1, use_transit;

  scroll_data = [
    {
      part0: 510,
      part1: 510,
      part2: 300,
      part3: 60,
      part4: 60,
      part5: 60
    }
  ];

  next_label_coord = 0;

  timeline_1 = null;

  window.i1start = function(sym) {
    if (timeline_1) {
      return;
    }
    sym.stop();
    return timeline_1 = sym;
  };

  $(document).ready(function() {
    var resize_screen_handler, window_height, window_width;
    window_height = $(window).height();
    window_width = $(window).width();
    resize_screen_handler = function() {
      window_height = $(window).height();
      window_width = $(window).width();
      $('.eighth_floor').css('height', window_height + 400 + 'px');
      return $('.popup1').css('top', window_height - 650 + 'px');
    };
    resize_screen_handler();
    return $(window).on('resize', resize_screen_handler);
  });

  timeStamp = new Date().getTime();

  is_next_play = false;

  $('body').on('mousewheel', function(e) {
    var timeNow, wheel;
    wheel = e.originalEvent.wheelDelta;
    timeNow = new Date().getTime();
    if (timeNow - timeStamp < 100) {
      timeStamp = timeNow;
      if (is_next_play && wheel > 0) {
        play_prev();
      }
      if (!is_next_play && wheel < 0) {
        play_next();
      }
      return;
    } else {
      timeStamp = timeNow;
      if (wheel < 0) {
        play_next();
      }
      if (wheel > 0) {
        play_prev();
      }
    }
    return e.preventDefault();
  });

  play_next = function() {
    is_next_play = true;
    return timeline_1.play();
  };

  play_prev = function() {
    is_next_play = false;
    return timeline_1.playReverse();
  };

  use_transit = function(selector, animate_object) {
    if ($(document).transit === void 0) {
      return $.getScript('scripts/jquery.transit.min.js', function() {
        return $(selector).transition(animate_object);
      });
    } else {
      return $(selector).transition(animate_object);
    }
  };

}).call(this);

/*
//@ sourceMappingURL=script.map
*/
