// Generated by CoffeeScript 1.6.3
(function() {
  $('.content').onepage_scroll({
    pagination: true
  });

  $('.slider').glide({
    arrows: false,
    nav: false,
    autoplay: false
  });

}).call(this);
